# Copy these secrets to your Streamlit Cloud app settings

# Environment flags
DEPLOYED = true
IS_CLOUD = true

# Supabase connection (if you want cloud database sync)
SUPABASE_URL = "https://oxgfxjhdguultqqrbwxa.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94Z2Z4amhkZ3V1bHRxcXJid3hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTg0MzQsImV4cCI6MjA2MTc5NDQzNH0.IAloyZDavDSkIyat3n9-DweNK65WhttTymfT7VzUqS4"

# Email configuration for quote sending (optional)
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USERNAME = "your-email@gmail.com"
EMAIL_PASSWORD = "your-app-password"
EMAIL_FROM = "InkStitchPress <your-email@gmail.com>"