# Copy these secrets to your Streamlit Cloud app settings

# Environment flags (minimal configuration for self-contained app)
DEPLOYED = true

# Email configuration for quote sending (optional)
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USERNAME = "your-email@gmail.com"
# EMAIL_PASSWORD = "your-app-password"
# EMAIL_FROM = "InkStitchPress <your-email@gmail.com>"